### ISSUE TITLE
TestNG | Retry Analyser brings inconsistency on the terminating launches on RP 

### ISSUE THREAD

**Issue by jonacarvalheiro** [reportportal/agent-java-testNG#95]
**Describe the bug**
If I had a retry analyser to an AnnotationTransformer, the launches start to be inconsistent regarding the terminating launch.  
I use v4 in k8  and works perfectly

**To Reproduce**
Retry.class
```
@Override
    public boolean retry(ITestResult iTestResult) {
        if (iTestResult.getStatus() == ITestResult.FAILURE) {                      //Check if test not succeed
           if (count < maxTry) {                            //Check if maxtry count is reached
                count++;                                     //Increase the maxTry count by 1
                //Mark test as failed

                return true;                                 //Tells TestNG to re-run the test
            }

        }
        return false;
    }
```

AnnotationTransformer.class

```
   @Override
    public void transform(ITestAnnotation annotation, Class testClass, Constructor testConstructor, Method testMethod) {
        annotation.setRetryAnalyzer(Retry.class);

    }
```

values.yaml

```
serviceindex:
  name: Index Service
  repository: reportportal/service-index
  tag: 5.0.3
  pullPolicy: Always
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 8080
    aanotations: {}

uat:
  repository: reportportal/service-authorization
  name: Authorization Service
  tag: 5.0.0-BETA-12
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 2048Mi
  sessionLiveTime: 86400
  service:
    type: ClusterIP
    port: 9999
    aanotations: {}

serviceui:
  repository: reportportal/service-ui
  tag: 5.0.0-BETA-12
  name: UI Service
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 8080
    aanotations: {}

serviceapi:
  repository: reportportal/service-api
  tag: 5.0.0-BETA-12
  name: API Service
  pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  service:
    type: ClusterIP
    port: 8585
    aanotations: {}

migrations:
  repository: reportportal/migrations
  tag: 5.0.0-BETA-8
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

serviceanalyzer:
  repository: reportportal/service-analyzer
  tag: 5.0.0-BETA-4
  name: Analyzer Service
  pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 8080
    aanotations: {}

rabbitmq:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    external: true
    address: <rabbitmq_chart_name>-rabbitmq-ha.default.svc.cluster.local
    port: 5672
    user: rabbitmq
    apiport: 15672
    apiuser: rabbitmq

postgresql:
  SecretName: ""
  installdep:
    enable: false
  endpoint:
    external: true
    cloudservice: false
    address: <postgresql_chart_name>-postgresql.default.svc.cluster.local
    port: 5432
    user: rpuser
    dbName: reportportal
    password:

elasticsearch:
  installdep:
    enable: false
  endpoint:
    external: true
    cloudservice: false
    address: <es_chart_name>-elasticsearch-coordinating-only.default.svc.cluster.local
    port: 9200

# Ingress configuration for the ui
# If you have installed ingress controller and want to expose application - set INGRESS.ENABLE to true.
# If you have some domain name set INGRESS.USEDOMAINNAME variable to true and set this fqdn to INGRESS.HOSTS
# If you don't have any domain names - set INGRESS.USEDOMAINNAME to false
ingress:
  enable: true
  # IF YOU HAVE SOME DOMAIN NAME SET INGRESS.USEDOMAINNAME to true
  usedomainname: false
  hosts:
    - reportportal.k8.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 128m

# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true


# RBAC is required for service-index in order to collect status/info over all services
rbac:
  create: true
  serviceAccount:
      create: true
      name: reportportal

rp:
  infoEndpoint: "/info"
  healthEndpoint: "/health"

```

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [77.0.3865.90]
